### ISSUE TITLE
Book Cover: Select Image file type

### ISSUE THREAD

**Issue by cydajufree** [anasceym/falcon-agency-test#13]
Click to add book cover will prompt new page to select the image. 

Should have filter by image file type. Example: PNG, JPG, JPEG

![image](https://cloud.githubusercontent.com/assets/19330402/15222873/3331a6c8-18a4-11e6-9ff7-9f871380afc9.png)

**Comment by anasceym** [comment]
Fixed 7913ab0a50a549b3a916582433b13b6acd8f35af
