### ISSUE TITLE
Create New Book: Choose Author

### ISSUE THREAD

**Issue by cydajufree** [anasceym/falcon-agency-test#7]
1. How to add new author? 
   Is it only can choose existing author?

**Comment by anasceym** [comment]
Yes, the author is seeded into database manually. Because no requirement for that and timing issue :P

**Comment by cydajufree** [comment]
hm, not user friendly. May i know who has the authorize to create new book? Is it just admin or anyone also can create?

**Comment by anasceym** [comment]
Yes, of course not user friendly. 

The user (who is logged in) is considered admin. Will remove register links
