### ISSUE TITLE
Create New Book with Error Message

### ISSUE THREAD

**Issue by cydajufree** [anasceym/falcon-agency-test#8]
Test Steps:
1. Click on Create New Book
2. Key in Book's Title, Price, Book's front cover, description, release date, and genre.
3. Forgot to key in ISBN Number. What is ISBN Number? Is it unique? If mandatory fill, kindly put \* mandatory sign. 
4. Click on create button. 
5. System shows error message. 

![image](https://cloud.githubusercontent.com/assets/19330402/15221707/21d78672-189f-11e6-9903-1e9430aa9c09.png)

**Comment by anasceym** [comment]
Fixed 91c86144359faf13478fa2855466b4c61694a7a3
